spring:  profiles:    active: dev  datasource:    url: jdbc:mariadb://localhost:6666/course_schema    username: root    password: root    driverclassName: org.mariadb.jdbc.Driver  jpa:    hibernate:      ddl-auto: update
---spring:  profiles: dev  
server:
  port: 9090
  
default:
  config: 
    name: Spring Boot Demo
    author: Gabriel Calvo Vargas
    
config:
  name: Spring Boot Demo DEV
  rating: 5
  author: Gabriel Calvo Vargas DEV  ---spring:  profiles: qa  server:  port: 9191  default:  config:     name: Spring Boot Demo    author: Gabriel Calvo Vargas    config:  name: Spring Boot Demo QA  rating: 5  author: Gabriel Calvo Vargas QA